// SPDX-License-Identifier: MIT
pragma solidity ^0.8.14;

import "forge-std/Test.sol";
import "./utils.sol";
import "../src/PoC.sol";

/// @title Proof of Concept Test
/// @notice DO NOT USE ON ANY PUBLIC NETWORK
/// @dev https://book.getfoundry.sh/forge/writing-tests
contract PoCTest is Test {

    // ---------------------------------------------------------------------------------------------
    // VARIABLES

    /// @notice Attacker EOA address.
    /// @dev First address generated by Anvi. Private key is publicly known.
    address internal constant attacker = address(0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266);

    /// @notice Target address
    address internal constant target = address(0x45);

    /// @notice PoC address
    address internal poc;

    // ---------------------------------------------------------------------------------------------
    // SCENARIO SET UP

    /// @notice Sets up the environment. Deploy contracts here.
    function setUp() public {
        poc = address(new PoC(target));
    }

    // ---------------------------------------------------------------------------------------------
    // EXPLOIT TEST

    /// @notice Test the PoC here.
    function testPoC() public {
        // Every external contract call within `testPoC` starting here will have a `msg.sender` of
        // `attacker`.
        // https://book.getfoundry.sh/cheatcodes/start-prank
        vm.startPrank(attacker);

        // Exploit here

    }
}
